plugins {
    alias(libs.plugins.android.application)
    id 'com.google.gms.google-services'
}

android {
    namespace 'mostafa.hafezypoor.shikshap'
    compileSdk 36

    defaultConfig {

        applicationId "mostafa.hafezypoor.shikshap"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.com.google.android.material.material
    implementation libs.lottie
    implementation libs.retrofit
    implementation libs.converter.gson
    implementation libs.picasso
    implementation libs.blurview
    implementation libs.shimmer
    implementation libs.circleimageview
    implementation 'com.google.firebase:firebase-messaging:25.0.1'
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}